
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: nimbusclient2023

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js on local windows'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run test --publish
    npm run generate-report
  displayName: 'npm --publish test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/reports/junit_style_report.xml'
    searchFolder: .
  displayName: 'Publish the Test results'
